name: Kwiver

on:
  push:
    branches:
      - main
      - releases/**
  pull_request:
    branches:
      - main
      - releases/**
  workflow_dispatch:


concurrency:
  group: ci-${{github.ref}}-${{github.event.pull_request.number || github.run_number}}
  cancel-in-progress: true

jobs:
  make_linux_buildcache:
    strategy:
      matrix:
        arch: ["amd64", "arm64"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          fetch-depth: 1
      - name: Setup Qemu
        uses: docker/setup-qemu-action@v3
      - name: Run Docker Image
        run: |
          docker run --rm --platform linux/${{ matrix.arch }} -e GITHUB_USER=${{ github.actor }} -e GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} -v $(pwd):/utils ghcr.io/${{ github.repository }}/kwiver-spack-build-base:${{ matrix.arch }} /utils/create_buildcache.sh

  make-mac-buildcache:
    runs-on: macos-latest
    env:
      GITHUB_USER: ${{ github.actor }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          fetch-depth: 1
      - name: Checkout Kwiver
        run: |
          git clone --branch spackify-fletch-support --single-branch https://gitlab.kitware.com/kwiver/kwiver
      - name: Setup Spack
        uses: spack/setup-spack@v3
        with:
          spack_ref: releases/v1.1
          packages_ref: releases/v2025.06
          buildcache: true
      - name: Build Binaries
        shell: spack-bash {0}
        run: |
            spack env activate ./kwiver
            spack concretize
            spack install -j10
      - name: Push to mirror
        shell: spack-bash {0}
        run: |
            spack env activate ./kwiver
            spack buildcache --push --update-index --with-build-dependencies fletch-buildcache



            
